/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_SCHEMA_PB_H_INCLUDED
#define PB_SCHEMA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Wrapper_DataType {
    Wrapper_DataType_SPEED = 0,
    Wrapper_DataType_FORCE = 1,
    Wrapper_DataType_IMU = 2,
    Wrapper_DataType_POWER = 3,
    Wrapper_DataType_TEMPERATURE = 4,
    Wrapper_DataType_WIND = 5,
    Wrapper_DataType_VESC = 6,
    Wrapper_DataType_SETPOINT = 7,
    Wrapper_DataType_BLADE = 8,
    Wrapper_DataType_TURBINECONTROL = 9
} Wrapper_DataType;

typedef enum _Setpoint_Origin {
    Setpoint_Origin_WEB = 0,
    Setpoint_Origin_ESP = 1
} Setpoint_Origin;

typedef enum _TurbineControl_Command {
    TurbineControl_Command_Stop = 0,
    TurbineControl_Command_Auto = 1,
    TurbineControl_Command_Speed = 2,
    TurbineControl_Command_Pos = 3,
    TurbineControl_Command_Current = 4
} TurbineControl_Command;

/* Struct definitions */
typedef struct _BladeControl {
    int64_t time;
    float pitch1;
    float pitch2;
    float pitch3;
    float collectivePitch;
} BladeControl;

typedef struct _Force {
    int64_t time;
    float force;
    int32_t id;
} Force;

typedef struct _Power {
    int64_t time;
    float current;
    float voltage;
} Power;

typedef struct _Quaternion {
    float x;
    float y;
    float z;
    float w;
} Quaternion;

typedef struct _Setpoint {
    int64_t time;
    float RPM;
    float current;
    Setpoint_Origin origin;
} Setpoint;

typedef struct _Speed {
    int64_t time;
    float RPM;
} Speed;

typedef struct _Temperature {
    int64_t time;
    float temperature;
} Temperature;

typedef struct _TurbineControl {
    int64_t time;
    float value;
    TurbineControl_Command command;
} TurbineControl;

typedef struct _Vector3 {
    float x;
    float y;
    float z;
} Vector3;

typedef struct _Vesc {
    int64_t time;
    float avgMotorCurrent;
    float avgInputCurrent;
    float dutyCycleNow;
    int32_t rpm;
    float inpVoltage;
    float ampHours;
    float ampHoursCharged;
    int32_t tachometer;
    int32_t tachometerAbs;
} Vesc;

typedef struct _Wind {
    int64_t time;
    float speed;
    float direction;
} Wind;

typedef struct _Wrapper {
    Wrapper_DataType type;
    pb_callback_t data;
} Wrapper;

typedef struct _Imu {
    int64_t time;
    bool has_acc;
    Vector3 acc;
    bool has_gyro;
    Vector3 gyro;
    bool has_orientation;
    Quaternion orientation;
} Imu;


/* Helper constants for enums */
#define _Wrapper_DataType_MIN Wrapper_DataType_SPEED
#define _Wrapper_DataType_MAX Wrapper_DataType_TURBINECONTROL
#define _Wrapper_DataType_ARRAYSIZE ((Wrapper_DataType)(Wrapper_DataType_TURBINECONTROL+1))

#define _Setpoint_Origin_MIN Setpoint_Origin_WEB
#define _Setpoint_Origin_MAX Setpoint_Origin_ESP
#define _Setpoint_Origin_ARRAYSIZE ((Setpoint_Origin)(Setpoint_Origin_ESP+1))

#define _TurbineControl_Command_MIN TurbineControl_Command_Stop
#define _TurbineControl_Command_MAX TurbineControl_Command_Current
#define _TurbineControl_Command_ARRAYSIZE ((TurbineControl_Command)(TurbineControl_Command_Current+1))


/* Initializer values for message structs */
#define Wrapper_init_default                     {_Wrapper_DataType_MIN, {{NULL}, NULL}}
#define Speed_init_default                       {0, 0}
#define Force_init_default                       {0, 0, 0}
#define Power_init_default                       {0, 0, 0}
#define Imu_init_default                         {0, false, Vector3_init_default, false, Vector3_init_default, false, Quaternion_init_default}
#define Temperature_init_default                 {0, 0}
#define Wind_init_default                        {0, 0, 0}
#define Vector3_init_default                     {0, 0, 0}
#define Quaternion_init_default                  {0, 0, 0, 0}
#define Vesc_init_default                        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Setpoint_init_default                    {0, 0, 0, _Setpoint_Origin_MIN}
#define BladeControl_init_default                {0, 0, 0, 0, 0}
#define TurbineControl_init_default              {0, 0, _TurbineControl_Command_MIN}
#define Wrapper_init_zero                        {_Wrapper_DataType_MIN, {{NULL}, NULL}}
#define Speed_init_zero                          {0, 0}
#define Force_init_zero                          {0, 0, 0}
#define Power_init_zero                          {0, 0, 0}
#define Imu_init_zero                            {0, false, Vector3_init_zero, false, Vector3_init_zero, false, Quaternion_init_zero}
#define Temperature_init_zero                    {0, 0}
#define Wind_init_zero                           {0, 0, 0}
#define Vector3_init_zero                        {0, 0, 0}
#define Quaternion_init_zero                     {0, 0, 0, 0}
#define Vesc_init_zero                           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Setpoint_init_zero                       {0, 0, 0, _Setpoint_Origin_MIN}
#define BladeControl_init_zero                   {0, 0, 0, 0, 0}
#define TurbineControl_init_zero                 {0, 0, _TurbineControl_Command_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define BladeControl_time_tag                    1
#define BladeControl_pitch1_tag                  2
#define BladeControl_pitch2_tag                  3
#define BladeControl_pitch3_tag                  4
#define BladeControl_collectivePitch_tag         5
#define Force_time_tag                           1
#define Force_force_tag                          2
#define Force_id_tag                             3
#define Power_time_tag                           1
#define Power_current_tag                        2
#define Power_voltage_tag                        3
#define Quaternion_x_tag                         1
#define Quaternion_y_tag                         2
#define Quaternion_z_tag                         3
#define Quaternion_w_tag                         4
#define Setpoint_time_tag                        1
#define Setpoint_RPM_tag                         2
#define Setpoint_current_tag                     3
#define Setpoint_origin_tag                      4
#define Speed_time_tag                           1
#define Speed_RPM_tag                            2
#define Temperature_time_tag                     1
#define Temperature_temperature_tag              2
#define TurbineControl_time_tag                  1
#define TurbineControl_value_tag                 2
#define TurbineControl_command_tag               3
#define Vector3_x_tag                            1
#define Vector3_y_tag                            2
#define Vector3_z_tag                            3
#define Vesc_time_tag                            1
#define Vesc_avgMotorCurrent_tag                 2
#define Vesc_avgInputCurrent_tag                 3
#define Vesc_dutyCycleNow_tag                    4
#define Vesc_rpm_tag                             5
#define Vesc_inpVoltage_tag                      6
#define Vesc_ampHours_tag                        7
#define Vesc_ampHoursCharged_tag                 8
#define Vesc_tachometer_tag                      9
#define Vesc_tachometerAbs_tag                   10
#define Wind_time_tag                            1
#define Wind_speed_tag                           2
#define Wind_direction_tag                       3
#define Wrapper_type_tag                         1
#define Wrapper_data_tag                         2
#define Imu_time_tag                             1
#define Imu_acc_tag                              2
#define Imu_gyro_tag                             3
#define Imu_orientation_tag                      4

/* Struct field encoding specification for nanopb */
#define Wrapper_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define Wrapper_CALLBACK pb_default_field_callback
#define Wrapper_DEFAULT NULL

#define Speed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    RPM,               2)
#define Speed_CALLBACK NULL
#define Speed_DEFAULT NULL

#define Force_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    force,             2) \
X(a, STATIC,   SINGULAR, INT32,    id,                3)
#define Force_CALLBACK NULL
#define Force_DEFAULT NULL

#define Power_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           3)
#define Power_CALLBACK NULL
#define Power_DEFAULT NULL

#define Imu_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  acc,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gyro,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  orientation,       4)
#define Imu_CALLBACK NULL
#define Imu_DEFAULT NULL
#define Imu_acc_MSGTYPE Vector3
#define Imu_gyro_MSGTYPE Vector3
#define Imu_orientation_MSGTYPE Quaternion

#define Temperature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2)
#define Temperature_CALLBACK NULL
#define Temperature_DEFAULT NULL

#define Wind_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    direction,         3)
#define Wind_CALLBACK NULL
#define Wind_DEFAULT NULL

#define Vector3_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define Vector3_CALLBACK NULL
#define Vector3_DEFAULT NULL

#define Quaternion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    w,                 4)
#define Quaternion_CALLBACK NULL
#define Quaternion_DEFAULT NULL

#define Vesc_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    avgMotorCurrent,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    avgInputCurrent,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    dutyCycleNow,      4) \
X(a, STATIC,   SINGULAR, INT32,    rpm,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    inpVoltage,        6) \
X(a, STATIC,   SINGULAR, FLOAT,    ampHours,          7) \
X(a, STATIC,   SINGULAR, FLOAT,    ampHoursCharged,   8) \
X(a, STATIC,   SINGULAR, INT32,    tachometer,        9) \
X(a, STATIC,   SINGULAR, INT32,    tachometerAbs,    10)
#define Vesc_CALLBACK NULL
#define Vesc_DEFAULT NULL

#define Setpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    RPM,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           3) \
X(a, STATIC,   SINGULAR, UENUM,    origin,            4)
#define Setpoint_CALLBACK NULL
#define Setpoint_DEFAULT NULL

#define BladeControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch1,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch2,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch3,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    collectivePitch,   5)
#define BladeControl_CALLBACK NULL
#define BladeControl_DEFAULT NULL

#define TurbineControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    time,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, UENUM,    command,           3)
#define TurbineControl_CALLBACK NULL
#define TurbineControl_DEFAULT NULL

extern const pb_msgdesc_t Wrapper_msg;
extern const pb_msgdesc_t Speed_msg;
extern const pb_msgdesc_t Force_msg;
extern const pb_msgdesc_t Power_msg;
extern const pb_msgdesc_t Imu_msg;
extern const pb_msgdesc_t Temperature_msg;
extern const pb_msgdesc_t Wind_msg;
extern const pb_msgdesc_t Vector3_msg;
extern const pb_msgdesc_t Quaternion_msg;
extern const pb_msgdesc_t Vesc_msg;
extern const pb_msgdesc_t Setpoint_msg;
extern const pb_msgdesc_t BladeControl_msg;
extern const pb_msgdesc_t TurbineControl_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Wrapper_fields &Wrapper_msg
#define Speed_fields &Speed_msg
#define Force_fields &Force_msg
#define Power_fields &Power_msg
#define Imu_fields &Imu_msg
#define Temperature_fields &Temperature_msg
#define Wind_fields &Wind_msg
#define Vector3_fields &Vector3_msg
#define Quaternion_fields &Quaternion_msg
#define Vesc_fields &Vesc_msg
#define Setpoint_fields &Setpoint_msg
#define BladeControl_fields &BladeControl_msg
#define TurbineControl_fields &TurbineControl_msg

/* Maximum encoded size of messages (where known) */
/* Wrapper_size depends on runtime parameters */
#define Speed_size                               16
#define Force_size                               27
#define Power_size                               21
#define Imu_size                                 67
#define Temperature_size                         16
#define Wind_size                                21
#define Vector3_size                             15
#define Quaternion_size                          20
#define Vesc_size                                74
#define Setpoint_size                            23
#define BladeControl_size                        31
#define TurbineControl_size                      18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
