/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Wrapper, Wrapper, AUTO)


PB_BIND(Speed, Speed, AUTO)


PB_BIND(Force, Force, AUTO)


PB_BIND(Power, Power, AUTO)


PB_BIND(Imu, Imu, AUTO)


PB_BIND(Temperature, Temperature, AUTO)


PB_BIND(Wind, Wind, AUTO)


PB_BIND(Vector3, Vector3, AUTO)


PB_BIND(Quaternion, Quaternion, AUTO)




